# Generated by Django 6.0.2 on 2026-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_bilateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slots_filled',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='workers_needed',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
