# Generated by Django 6.0.2 on 2026-09-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
