# Generated by Django 6.0.2 on 2026-10-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_workos'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='approx_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='approx_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='phone_masked',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='preferred_payout',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
