# Generated by Django 6.0.2 on 2026-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_live_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
