"""
Django settings for Care_Nest project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import urllib.parse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file if present (never committed; see .env.example).
load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR.parent / ".env")
load_dotenv(BASE_DIR / ".env.local")
load_dotenv(BASE_DIR / ".vercel" / ".env.development.local")


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The key is read from the environment. A development-only fallback is used
# when DJANGO_SECRET_KEY is not set so the project still boots locally.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or (
    "dev-only-insecure-key-set-DJANGO_SECRET_KEY-in-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,.vercel.app").split(",") if h.strip()
]
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://127.0.0.1:8000,http://localhost:8000,https://*.vercel.app",
    ).split(",")
    if o.strip()
]
vercel_host = os.getenv("VERCEL_URL", "").replace("https://", "").replace("http://", "").strip()
if vercel_host:
    ALLOWED_HOSTS.append(vercel_host)
    origin = f"https://{vercel_host}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)
for extra in ("carenest.vercel.app", "care-nest.vercel.app", "carenest.onrender.com"):
    if extra not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(extra)
    origin = f"https://{extra}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)
render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_host:
    if render_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_host)
    origin = f"https://{render_host}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)
if os.getenv("RENDER") and ".onrender.com" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".onrender.com")
if os.getenv("RENDER"):
    wildcard = "https://*.onrender.com"
    if wildcard not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(wildcard)

if DEBUG:
    if "*" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append("*")
    for origin in (
        "http://10.0.2.2:8000",
        "http://10.0.3.2:8000",
        "http://127.0.0.1:8000",
        "http://localhost:8000",
    ):
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

if os.getenv("VERCEL") or os.getenv("RENDER"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
    SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
    CSRF_FAILURE_VIEW = "apps.accounts.views.csrf_failure"


# Application definition

INSTALLED_APPS = [
    "rest_framework",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "apps.accounts",
    "apps.profiles",
    "apps.jobs",
    "apps.contracts",
    "apps.wallet",
    "apps.dashboard",
    "apps.core",
    "apps.ussd_app",
    "apps.courses.apps.CoursesConfig",
    "apps.agentic_core.apps.AgenticCoreConfig",
]

AUTH_USER_MODEL = "accounts.User"


REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"]
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Care_Nest.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "builtins": ["apps.core.templatetags.money"],
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Care_Nest.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "TEST": {"NAME": ":memory:"},
    }
}

_database_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL") or os.getenv("POSTGRES_PRISMA_URL")
if _database_url:
    url = urllib.parse.urlparse(_database_url)
    query = urllib.parse.parse_qs(url.query)
    sslmode = os.getenv("POSTGRES_SSLMODE") or (query.get("sslmode") or [None])[0]
    host = url.hostname or ""
    if not sslmode:
        internal_render = bool(os.getenv("RENDER")) and "render.com" in host and "-a." not in host
        sslmode = "disable" if internal_render else "require"
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": urllib.parse.unquote(url.path.lstrip("/")).split("?")[0],
            "USER": urllib.parse.unquote(url.username or ""),
            "PASSWORD": urllib.parse.unquote(url.password or ""),
            "HOST": url.hostname,
            "PORT": str(url.port or "5432"),
            "CONN_MAX_AGE": 60 if os.getenv("RENDER") else 0,
            "OPTIONS": {"sslmode": sslmode},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "role-selection"

# ---------------------------------------------------------------------------
# Stellar / Soroban (trust & settlement layer)
# ---------------------------------------------------------------------------
STELLAR_NETWORK = os.getenv("STELLAR_NETWORK", "testnet")  # testnet | futurenet | public
STELLAR_RPC_URL = os.getenv("STELLAR_RPC_URL", "https://soroban-testnet.stellar.org")
STELLAR_HORIZON_URL = os.getenv("STELLAR_HORIZON_URL", "https://horizon-testnet.stellar.org")
STELLAR_NETWORK_PASSPHRASE = os.getenv(
    "STELLAR_NETWORK_PASSPHRASE", "Test SDF Network ; September 2015"
)
STELLAR_FRIENDBOT_URL = os.getenv("STELLAR_FRIENDBOT_URL", "https://friendbot.stellar.org")
# Deployed CareNest WorkContract id (C...). Empty => on-chain actions are unavailable
# and the UI falls back to clearly-labelled DEMO DATA.
CARENEST_CONTRACT_ID = os.getenv("CARENEST_CONTRACT_ID", "")
# SAC address of the settlement token (defaults to native XLM SAC on testnet).
CARENEST_TOKEN_CONTRACT_ID = os.getenv(
    "CARENEST_TOKEN_CONTRACT_ID",
    "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
)
CARENEST_TOKEN_SYMBOL = os.getenv("CARENEST_TOKEN_SYMBOL", "XLM")
CARENEST_TOKEN_DECIMALS = int(os.getenv("CARENEST_TOKEN_DECIMALS", "7"))
# Optional server-held testnet signing keys used ONLY for the guided demo when a
# browser wallet is not available. Never use funded mainnet keys here.
STELLAR_DEMO_EMPLOYER_SECRET = os.getenv("STELLAR_DEMO_EMPLOYER_SECRET", "")
STELLAR_DEMO_WORKER_SECRET = os.getenv("STELLAR_DEMO_WORKER_SECRET", "")
STELLAR_ARBITER_SECRET = os.getenv("STELLAR_ARBITER_SECRET", "")
# When true, blockchain calls are never attempted and recorded fixtures are used.
CARENEST_FORCE_DEMO_MODE = env_bool("CARENEST_FORCE_DEMO_MODE", default=False)
STELLAR_EXPLORER_BASE = os.getenv(
    "STELLAR_EXPLORER_BASE", "https://stellar.expert/explorer/testnet"
)

# ---------------------------------------------------------------------------
# Omega / ASI Alliance inference (AI infrastructure layer)
# ---------------------------------------------------------------------------
# Omega (singnet/Omega) uses the `ASI_API_KEY` convention for its ASICloud
# provider. CareNest talks to the same OpenAI-compatible inference endpoint
# through apps.agentic_core.omega_adapter so the rest of the app never depends
# on a specific vendor SDK.
OMEGA_LLM_BASE_URL = os.getenv("OMEGA_LLM_BASE_URL", "https://llm.c.singularitynet.io/v1")
OMEGA_LLM_MODEL = os.getenv("OMEGA_LLM_MODEL", "asi1-mini")
OMEGA_LLM_TIMEOUT = float(os.getenv("OMEGA_LLM_TIMEOUT", "40"))
OMEGA_LLM_ENABLED = env_bool("OMEGA_LLM_ENABLED", default=bool(os.getenv("ASI_API_KEY")))

# ---------------------------------------------------------------------------
# CareNest commercial rules (authoritative server-side)
# ---------------------------------------------------------------------------
from decimal import Decimal

CARENEST_PLATFORM_FEE_PERCENT = Decimal(os.getenv("CARENEST_PLATFORM_FEE_PERCENT", "5"))
CARENEST_UPSKILLING_RECOVERY_PERCENT = Decimal(os.getenv("CARENEST_UPSKILLING_RECOVERY_PERCENT", "20"))

# Maps — browser key only, never a secret. Empty => Leaflet/OSM.
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")
GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_OAUTH_REDIRECT_URI = os.getenv("GOOGLE_OAUTH_REDIRECT_URI", "")
CARTO_API_KEY = os.getenv("CARTO_API_KEY", "")
MAP_PROVIDER = os.getenv("MAP_PROVIDER", "leaflet")

# Market prices
PRICE_FEED_URL = os.getenv("PRICE_FEED_URL", "https://api.coingecko.com/api/v3/simple/price")
FX_FALLBACK_URL = os.getenv("FX_FALLBACK_URL", "https://api.frankfurter.app/latest")
PRICE_CACHE_SECONDS = int(os.getenv("PRICE_CACHE_SECONDS", "60"))
PRICE_STALE_SECONDS = int(os.getenv("PRICE_STALE_SECONDS", "300"))

# Supabase (optional mirror + storage). Secret key is server-side only.
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_PUBLISHABLE_KEY = os.getenv("SUPABASE_PUBLISHABLE_KEY", "")
SUPABASE_SECRET_KEY = os.getenv("SUPABASE_SECRET_KEY", "")
SUPABASE_JWKS_URL = os.getenv("SUPABASE_JWKS_URL", "")
SUPABASE_EXPOSE_PUBLISHABLE = env_bool("SUPABASE_EXPOSE_PUBLISHABLE", default=False)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "loggers": {
        "carenest": {"handlers": ["console"], "level": os.getenv("CARENEST_LOG_LEVEL", "INFO")},
    },
}
