# Generated by Django 6.0.2 on 2026-10-01 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
                ('duration_hours', models.FloatField(default=8, help_text='Estimated duration in hours')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('recovery_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('commission_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('repaying', 'Repaying'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'worker')},
            },
        ),
    ]
