# Generated by Django 6.0.2 on 2026-09-30 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_workos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision_type', models.CharField(choices=[('PARSE_REQUIREMENT', 'Parse Requirement'), ('RECOMMEND_WORKERS', 'Recommend Workers'), ('PREPARE_CONTRACT', 'Prepare Contract'), ('REQUEST_CONTRACT_APPROVAL', 'Request Contract Approval'), ('REQUEST_FUNDING_APPROVAL', 'Request Funding Approval'), ('REQUEST_EMPLOYER_APPROVAL', 'Request Employer Approval'), ('RECORD_CHAIN_EVENT', 'Record Chain Event'), ('RECORD_RESULT', 'Record Result'), ('ISSUE_CREDENTIAL', 'Issue Credential'), ('FLAG_DISPUTE', 'Flag Dispute'), ('EXPLAIN_STATE', 'Explain State'), ('NOTIFY', 'Notify'), ('NO_ACTION', 'No Action')], max_length=40)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('decision', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('action', models.CharField(blank=True, default='', max_length=80)),
                ('approval_required', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='NOT_REQUIRED', max_length=16)),
                ('financial', models.BooleanField(default=False, help_text='True if the prepared action moves funds')),
                ('financial_action_executed', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=64)),
                ('data_source', models.CharField(choices=[('LIVE_TESTNET', 'Live testnet'), ('DEMO_DATA', 'Demo data'), ('OFF_CHAIN', 'Off-chain only')], default='OFF_CHAIN', max_length=16)),
                ('model_used', models.CharField(blank=True, default='', max_length=80)),
                ('llm_used', models.BooleanField(default=False)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_decisions', to='contracts.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('CREATE_AGREEMENT', 'Create Agreement'), ('FUND_ESCROW', 'Fund Escrow'), ('RELEASE_PAYMENT', 'Release Payment'), ('RESOLVE_DISPUTE', 'Resolve Dispute'), ('CANCEL_AGREEMENT', 'Cancel Agreement'), ('ISSUE_CREDENTIAL', 'Issue Credential')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('summary', models.TextField()),
                ('prepared_action', models.JSONField(blank=True, default=dict, help_text='Contract function + arguments prepared by the agent')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('tx_hash', models.CharField(blank=True, default='', max_length=64)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('LIVE_TESTNET', 'Live testnet'), ('DEMO_DATA', 'Demo data'), ('OFF_CHAIN', 'Off-chain only')], default='LIVE_TESTNET', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='contracts.contract')),
                ('requested_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_agent_approvals', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='agentic_core.agentdecision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_role', models.CharField(blank=True, default='', max_length=20)),
                ('workflow_stage', models.CharField(default='intake', max_length=40)),
                ('contract_state', models.CharField(choices=[('DRAFT', 'Draft'), ('CREATED', 'Created'), ('FUNDED', 'Funded'), ('WORKING', 'Working'), ('SUBMITTED', 'Submitted'), ('APPROVAL_PENDING', 'Approval Pending'), ('DISPUTED', 'Disputed'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('engagement_context', models.JSONField(blank=True, default=dict)),
                ('previous_actions', models.JSONField(blank=True, default=list)),
                ('unresolved_tasks', models.JSONField(blank=True, default=list)),
                ('important_decisions', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_event_ledger', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_memory', to='contracts.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'agent memories',
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('ussd', 'USSD'), ('system', 'System / scheduler')], default='web', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='contracts.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='agentdecision',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='agentic_core.agentsession'),
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=80)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to='contracts.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='agentic_core.agentdecision')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='agentic_core.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StellarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=80, unique=True)),
                ('contract_id', models.CharField(db_index=True, max_length=56)),
                ('ledger', models.BigIntegerField(db_index=True)),
                ('ledger_closed_at', models.DateTimeField(blank=True, null=True)),
                ('tx_hash', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('chain_engagement_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('data_source', models.CharField(choices=[('LIVE_TESTNET', 'Live testnet'), ('DEMO_DATA', 'Demo data'), ('OFF_CHAIN', 'Off-chain only')], default='LIVE_TESTNET', max_length=16)),
                ('processed', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stellar_events', to='contracts.contract')),
            ],
            options={
                'ordering': ['ledger', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_type', models.CharField(max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('completion_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('DISPUTED_RESOLVED', 'Disputed Resolved')], default='COMPLETED', max_length=24)),
                ('employer_confirmation', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('RELEASED', 'Released'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], default='RELEASED', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('credential_hash', models.CharField(db_index=True, max_length=64)),
                ('on_chain_reference', models.CharField(blank=True, default='', max_length=80)),
                ('transaction_hash', models.CharField(blank=True, default='', max_length=64)),
                ('release_tx_hash', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('data_source', models.CharField(choices=[('LIVE_TESTNET', 'Live testnet'), ('DEMO_DATA', 'Demo data'), ('OFF_CHAIN', 'Off-chain only')], default='LIVE_TESTNET', max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_credential', to='contracts.contract')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
