# Generated by Django 6.0.2 on 2026-09-30 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='contract',
            name='chain_status',
            field=models.CharField(db_index=True, default='DRAFT', max_length=32),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_address',
            field=models.CharField(blank=True, default='', max_length=56),
        ),
        migrations.AddField(
            model_name='contract',
            name='create_tx_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='credential_tx_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='KES', max_length=8),
        ),
        migrations.AddField(
            model_name='contract',
            name='data_source',
            field=models.CharField(choices=[('LIVE_TESTNET', 'Live testnet'), ('DEMO_DATA', 'Demo data')], default='LIVE_TESTNET', max_length=16),
        ),
        migrations.AddField(
            model_name='contract',
            name='employer_wallet',
            field=models.CharField(blank=True, default='', max_length=56),
        ),
        migrations.AddField(
            model_name='contract',
            name='engagement_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Engagement id inside the Soroban contract', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='fund_tx_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='release_tx_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='submit_tx_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='token_amount',
            field=models.BigIntegerField(blank=True, help_text='Escrow amount in token base units (stroops)', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='token_symbol',
            field=models.CharField(default='XLM', max_length=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='work_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='worker_wallet',
            field=models.CharField(blank=True, default='', max_length=56),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
