# Generated by Django 6.0.2 on 2026-10-01 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_phase2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="employer_terms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contract",
            name="worker_terms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contract",
            name="worker_hours_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contract",
            name="worker_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="bound_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ShiftAttendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked_in_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("check_in_note", models.CharField(blank=True, default="", max_length=255)),
                ("check_out_note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="contracts.contract",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-checked_in_at"]},
        ),
        migrations.CreateModel(
            name="ServiceInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(blank=True, default="", max_length=32, unique=True)),
                ("description", models.CharField(default="CareNest upskilling recovery", max_length=255)),
                ("eligible_earnings", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("recovery_percentage", models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ("recovery_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("remaining_training_after", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="KES", max_length=8)),
                ("line_items", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("issued", "Issued"), ("settled", "Settled"), ("void", "Void")],
                        default="issued",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_invoices",
                        to="contracts.contract",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-issued_at"]},
        ),
    ]
