# Generated by Django 6.0.2 on 2026-10-02 16:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_bilateral'),
        ('jobs', '0004_marketplace_ux'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftattendance',
            name='employer_verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shiftattendance',
            name='employer_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftattendance',
            name='employer_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftattendance',
            name='work_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('payment', 'Payment'), ('scope', 'Work scope'), ('conduct', 'Conduct'), ('other', 'Other')], default='other', max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('unresolved', 'Unresolved'), ('settled', 'Settled')], db_index=True, default='ongoing', max_length=16)),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_disputes', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contracts.contract')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='jobs.job')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('check_in', 'Check in'), ('check_out', 'Check out'), ('work_submitted', 'Work submitted'), ('work_approved', 'Work approved'), ('dispute', 'Dispute'), ('contract', 'Contract')], default='contract', max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contracts.contract')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
