# Generated by Django 6.0.2 on 2026-09-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wallet',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='stellar_address',
            field=models.CharField(blank=True, db_index=True, default='', max_length=56),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_provider',
            field=models.CharField(blank=True, choices=[('', 'Not connected'), ('freighter', 'Freighter'), ('xbull', 'xBull'), ('albedo', 'Albedo'), ('lobstr', 'LOBSTR'), ('hana', 'Hana'), ('walletconnect', 'WalletConnect'), ('demo', 'Demo signer (server-held testnet key)'), ('manual', 'Manual public key')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
