# Generated by Django 6.0.2 on 2026-10-01 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_phase2'),
        ('wallet', '0002_workos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='KES', max_length=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='worker_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wallet',
            name='chain',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('stellar', 'Stellar'), ('evm', 'EVM')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='wallet',
            name='connection_status',
            field=models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('wrong_network', 'Wrong network'), ('unsupported', 'Unsupported wallet'), ('pending', 'Pending'), ('failed', 'Transaction failed'), ('confirmed', 'Transaction confirmed')], default='disconnected', max_length=24),
        ),
        migrations.AddField(
            model_name='wallet',
            name='evm_address',
            field=models.CharField(blank=True, db_index=True, default='', max_length=42),
        ),
        migrations.AddField(
            model_name='wallet',
            name='network',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_provider',
            field=models.CharField(blank=True, choices=[('', 'Not connected'), ('freighter', 'Freighter'), ('xbull', 'xBull'), ('albedo', 'Albedo'), ('lobstr', 'LOBSTR'), ('hana', 'Hana'), ('metamask', 'MetaMask'), ('walletconnect', 'WalletConnect'), ('injected_evm', 'Injected EVM'), ('demo', 'Demo signer (server-held testnet key)'), ('manual', 'Manual public key')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('worker_net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upskilling_recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('worker_payout_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FUNDED', 'Funded'), ('SETTLED', 'Settled'), ('FEE_CAPTURED', 'Fee captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], db_index=True, default='PENDING', max_length=16)),
                ('payout_method', models.CharField(blank=True, default='', max_length=16)),
                ('settlement_reference', models.CharField(blank=True, default='', max_length=80)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_settlements', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='contracts.contract')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='wallet.settlement'),
        ),
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('stellar', 'Blockchain wallet'), ('mpesa', 'M-Pesa')], max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=24)),
                ('masked_identifier', models.CharField(blank=True, default='', max_length=64)),
                ('identifier_hash', models.CharField(blank=True, default='', max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('last_reference', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'method_type')},
            },
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['status', 'created_at'], name='wallet_sett_status_28a118_idx'),
        ),
    ]
