# Generated by Django 6.0.2 on 2026-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_phase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='onchain_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='wallet',
            name='onchain_symbol',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='onchain_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
